# Generated by Django 4.1.7 on 2023-03-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='desc',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='discount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
